package config

import (
	"fmt"
	"strings"

	"sysmon-web/internal/models"
)

// Generate generates sysmon.conf format from config
func Generate(config *models.Config) (string, error) {
	if config == nil {
		return "", fmt.Errorf("config is nil")
	}

	var sb strings.Builder

	// Header comment
	sb.WriteString("# Sysmon Configuration\n")
	sb.WriteString("# Generated by sysmon-web\n\n")

	// Global settings
	if config.Global.ClientPort > 0 {
		sb.WriteString(fmt.Sprintf("clientport %d\n", config.Global.ClientPort))
	}
	if config.Global.SNMPTrapPort > 0 {
		sb.WriteString(fmt.Sprintf("snmptrapport %d\n", config.Global.SNMPTrapPort))
	}
	if config.Global.CheckInterval > 0 {
		sb.WriteString(fmt.Sprintf("checkinterval %d\n", config.Global.CheckInterval))
	}
	if config.Global.DisableICMP {
		sb.WriteString("disableicmp\n")
	}
	sb.WriteString("\n")

	// Hosts
	for _, host := range config.Hosts {
		sb.WriteString(fmt.Sprintf("monitor %s\n", host.Hostname))

		if host.Contact != "" {
			sb.WriteString(fmt.Sprintf("  contact %s\n", host.Contact))
		}

		if host.Paused {
			sb.WriteString("  pause\n")
		}

		// Checks
		for _, check := range host.Checks {
			switch check.Type {
			case "ping":
				sb.WriteString("  ping\n")

			case "pingv6":
				sb.WriteString("  pingv6\n")

			case "tcp":
				sb.WriteString(fmt.Sprintf("  tcp %d\n", check.Port))

			case "udp":
				sb.WriteString(fmt.Sprintf("  udp %d\n", check.Port))

			case "http":
				if check.Port > 0 && check.Port != 80 {
					sb.WriteString(fmt.Sprintf("  http %d\n", check.Port))
				} else {
					sb.WriteString("  http\n")
				}

			case "https":
				if check.Port > 0 && check.Port != 443 {
					sb.WriteString(fmt.Sprintf("  https %d\n", check.Port))
				} else {
					sb.WriteString("  https\n")
				}

			case "smtp":
				sb.WriteString("  smtp\n")

			case "pop3":
				sb.WriteString("  pop3\n")

			case "imap":
				sb.WriteString("  imap\n")

			case "dns":
				sb.WriteString("  dns\n")

			case "ssh":
				sb.WriteString("  ssh\n")

			case "snmp":
				if oid, ok := check.Options["oid"].(string); ok {
					sb.WriteString(fmt.Sprintf("  snmp %s\n", oid))
				}

			case "rtt":
				sb.WriteString("  rtt\n")

			case "pktloss":
				if threshold, ok := check.Options["threshold"].(float64); ok {
					sb.WriteString(fmt.Sprintf("  pktloss %.1f\n", threshold))
				} else {
					sb.WriteString("  pktloss 5.0\n")
				}
			}
		}

		sb.WriteString("\n")
	}

	return sb.String(), nil
}

// Validate validates a config
func Validate(config *models.Config) error {
	if config == nil {
		return fmt.Errorf("config is nil")
	}

	// Check required global settings
	if config.Global.ClientPort <= 0 || config.Global.ClientPort > 65535 {
		return fmt.Errorf("invalid client port: %d", config.Global.ClientPort)
	}

	// Check hosts
	if len(config.Hosts) == 0 {
		return fmt.Errorf("no hosts configured")
	}

	hostnames := make(map[string]bool)
	for _, host := range config.Hosts {
		// Check hostname
		if host.Hostname == "" {
			return fmt.Errorf("host has empty hostname")
		}

		// Check for duplicates
		if hostnames[host.Hostname] {
			return fmt.Errorf("duplicate hostname: %s", host.Hostname)
		}
		hostnames[host.Hostname] = true

		// Validate contact email
		if host.Contact != "" {
			// Basic email validation: must have @ with non-empty parts before and after
			parts := strings.Split(host.Contact, "@")
			if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
				return fmt.Errorf("invalid contact email for %s: %s (must have format: user@domain)", host.Hostname, host.Contact)
			}
			// Domain part should have at least one dot
			if !strings.Contains(parts[1], ".") {
				return fmt.Errorf("invalid contact email domain for %s: %s (domain must contain a dot)", host.Hostname, host.Contact)
			}
		}

		// Check that host has at least one check
		if len(host.Checks) == 0 {
			return fmt.Errorf("host %s has no checks", host.Hostname)
		}

		// Validate checks
		for _, check := range host.Checks {
			if check.Type == "" {
				return fmt.Errorf("check has empty type for host %s", host.Hostname)
			}

			// Validate port-based checks
			if (check.Type == "tcp" || check.Type == "udp") && (check.Port <= 0 || check.Port > 65535) {
				return fmt.Errorf("invalid port %d for %s check on host %s", check.Port, check.Type, host.Hostname)
			}
		}
	}

	return nil
}
