package config

import (
	"fmt"
	"strings"

	"sysmon-web/internal/models"
)

// Generate generates sysmon.conf format from config
func Generate(config *models.Config) (string, error) {
	if config == nil {
		return "", fmt.Errorf("config is nil")
	}

	var sb strings.Builder

	sb.WriteString("# Sysmon Configuration\n")
	sb.WriteString("# Generated by sysmon-web\n\n")

	// Root object for dependency tree
	if config.Root != "" {
		sb.WriteString(fmt.Sprintf("root = \"%s\";\n\n", config.Root))
	}

	// Global settings - use "config" prefix and semicolon terminators
	// matching the C parser's lex rules in parser.l

	if config.Global.CheckInterval > 0 {
		sb.WriteString(fmt.Sprintf("config queuetime %d;\n", config.Global.CheckInterval))
	}
	if config.Global.NumFailures > 0 {
		sb.WriteString(fmt.Sprintf("config numfailures %d;\n", config.Global.NumFailures))
	}
	if config.Global.MinNumFailures > 0 {
		sb.WriteString(fmt.Sprintf("config minnumfailures %d;\n", config.Global.MinNumFailures))
	}
	if config.Global.FlapTime > 0 {
		sb.WriteString(fmt.Sprintf("config flaptime %d;\n", config.Global.FlapTime))
	}
	if config.Global.MaxQueued > 0 {
		sb.WriteString(fmt.Sprintf("config maxqueued %d;\n", config.Global.MaxQueued))
	}
	if config.Global.PageInterval > 0 {
		sb.WriteString(fmt.Sprintf("config pageinterval %d;\n", config.Global.PageInterval))
	}
	if config.Global.DNSExpire > 0 {
		sb.WriteString(fmt.Sprintf("config dnsexpire %d;\n", config.Global.DNSExpire))
	}
	if config.Global.DNSLog > 0 {
		sb.WriteString(fmt.Sprintf("config dnslog %d;\n", config.Global.DNSLog))
	}
	if config.Global.HTMLRefresh > 0 {
		sb.WriteString(fmt.Sprintf("config html refresh %d;\n", config.Global.HTMLRefresh))
	}

	// Status file: "config statusfile html|text <path>;"
	if config.Global.StatusFile != "" {
		fileType := config.Global.StatusFileType
		if fileType == "" {
			fileType = "html"
		}
		sb.WriteString(fmt.Sprintf("config statusfile %s \"%s\";\n", fileType, config.Global.StatusFile))
	}
	if config.Global.StatusTempDir != "" {
		sb.WriteString(fmt.Sprintf("config statustempdir \"%s\";\n", config.Global.StatusTempDir))
	}
	if config.Global.CSSFile != "" {
		sb.WriteString(fmt.Sprintf("config cssfile \"%s\";\n", config.Global.CSSFile))
	}
	if config.Global.PidFile != "" {
		sb.WriteString(fmt.Sprintf("config pidfile \"%s\";\n", config.Global.PidFile))
	}
	if config.Global.Logging != "" {
		sb.WriteString(fmt.Sprintf("config logging %s;\n", config.Global.Logging))
	}
	if config.Global.SaveState != "" {
		sb.WriteString(fmt.Sprintf("config savestate \"%s\";\n", config.Global.SaveState))
	}

	// Sender / from (aliases in sysmond)
	if config.Global.Sender != "" {
		sb.WriteString(fmt.Sprintf("config sender \"%s\";\n", config.Global.Sender))
	}
	if config.Global.Subject != "" {
		sb.WriteString(fmt.Sprintf("config subject \"%s\";\n", config.Global.Subject))
	}
	if config.Global.NoSubject {
		sb.WriteString("config nosubject;\n")
	}
	if config.Global.ReplyTo != "" {
		sb.WriteString(fmt.Sprintf("config replyto \"%s\";\n", config.Global.ReplyTo))
	}
	if config.Global.ErrorsTo != "" {
		sb.WriteString(fmt.Sprintf("config errorsto \"%s\";\n", config.Global.ErrorsTo))
	}
	if config.Global.PMsg != "" {
		sb.WriteString(fmt.Sprintf("config pmesg \"%s\";\n", config.Global.PMsg))
	}
	if config.Global.AuthKey != "" {
		sb.WriteString(fmt.Sprintf("config authkey \"%s\";\n", config.Global.AuthKey))
	}
	if config.Global.DateFormat != "" {
		sb.WriteString(fmt.Sprintf("config date \"%s\";\n", config.Global.DateFormat))
	}

	// Colors
	if config.Global.UpColor != "" {
		sb.WriteString(fmt.Sprintf("config upcolor \"%s\";\n", config.Global.UpColor))
	}
	if config.Global.DownColor != "" {
		sb.WriteString(fmt.Sprintf("config downcolor \"%s\";\n", config.Global.DownColor))
	}
	if config.Global.RecentColor != "" {
		sb.WriteString(fmt.Sprintf("config recentcolor \"%s\";\n", config.Global.RecentColor))
	}

	// Boolean flags
	if config.Global.ShowUpAlso {
		sb.WriteString("config showupalso;\n")
	}
	if config.Global.DisableICMP {
		sb.WriteString("config disable_icmp;\n")
	}
	if config.Global.NoHeartbeat {
		sb.WriteString("config noheartbeat;\n")
	}
	if config.Global.NoLogConnects {
		sb.WriteString("config nologconnects;\n")
	}
	if config.Global.SNMPTrap {
		sb.WriteString("config snmp-trap;\n")
	}

	// Push notifications
	if config.Global.PushNotifications {
		sb.WriteString("config push-notifications;\n")
	}
	if config.Global.PushFCMServerKey != "" {
		sb.WriteString(fmt.Sprintf("config push-fcm-serverkey \"%s\";\n", config.Global.PushFCMServerKey))
	}
	if config.Global.PushAPNsCertFile != "" {
		sb.WriteString(fmt.Sprintf("config push-apns-certfile \"%s\";\n", config.Global.PushAPNsCertFile))
	}
	if config.Global.PushAPNsKeyFile != "" {
		sb.WriteString(fmt.Sprintf("config push-apns-keyfile \"%s\";\n", config.Global.PushAPNsKeyFile))
	}
	if config.Global.PushAPNsBundleID != "" {
		sb.WriteString(fmt.Sprintf("config push-apns-bundleid \"%s\";\n", config.Global.PushAPNsBundleID))
	}
	if config.Global.PushAPNsProduction {
		sb.WriteString("config push-apns-production;\n")
	}

	sb.WriteString("\n")

	// Spawn definitions
	for _, spawn := range config.Spawns {
		sb.WriteString("spawns {\n")
		sb.WriteString(fmt.Sprintf("  name \"%s\" {\n", spawn.Name))
		if spawn.Command != "" {
			sb.WriteString(fmt.Sprintf("    command \"%s\";\n", spawn.Command))
		}
		sb.WriteString("  };\n")
		sb.WriteString("};\n\n")
	}

	// Object definitions - use "object name { ... };" syntax
	for _, host := range config.Hosts {
		sb.WriteString(fmt.Sprintf("object %s {\n", host.Hostname))

		if host.IP != "" {
			sb.WriteString(fmt.Sprintf("\tip \"%s\";\n", host.IP))
		}
		if host.Type != "" {
			sb.WriteString(fmt.Sprintf("\ttype %s;\n", host.Type))
		} else if len(host.Checks) > 0 {
			sb.WriteString(fmt.Sprintf("\ttype %s;\n", host.Checks[0].Type))
		}
		if host.Port > 0 {
			sb.WriteString(fmt.Sprintf("\tport %d;\n", host.Port))
		} else if len(host.Checks) > 0 && host.Checks[0].Port > 0 {
			sb.WriteString(fmt.Sprintf("\tport %d;\n", host.Checks[0].Port))
		}
		if host.Notes != "" {
			sb.WriteString(fmt.Sprintf("\tdesc \"%s\";\n", host.Notes))
		}
		if host.Contact != "" {
			sb.WriteString(fmt.Sprintf("\tcontact \"%s\";\n", host.Contact))
		}
		if host.Dependencies != "" {
			sb.WriteString(fmt.Sprintf("\tdep \"%s\";\n", host.Dependencies))
		}
		if host.Group != "" {
			sb.WriteString(fmt.Sprintf("\tgroup \"%s\";\n", host.Group))
		}
		if host.Paused {
			sb.WriteString("\tpause;\n")
		}
		if host.Reverse {
			sb.WriteString("\treverse;\n")
		}

		// Per-object overrides
		if host.QueueTime > 0 {
			sb.WriteString(fmt.Sprintf("\tqueuetime %d;\n", host.QueueTime))
		}
		if host.NumFailures > 0 {
			sb.WriteString(fmt.Sprintf("\tnumfailures %d;\n", host.NumFailures))
		}
		if host.PageInterval > 0 {
			sb.WriteString(fmt.Sprintf("\tpageinterval %d;\n", host.PageInterval))
		}
		if host.ContactOn != "" {
			sb.WriteString(fmt.Sprintf("\tcontact_on %s;\n", host.ContactOn))
		}
		if host.Spawn != "" {
			sb.WriteString(fmt.Sprintf("\tspawn \"%s\";\n", host.Spawn))
		}
		if host.Command != "" {
			sb.WriteString(fmt.Sprintf("\tcommand \"%s\";\n", host.Command))
		}
		if host.PMsg != "" {
			sb.WriteString(fmt.Sprintf("\tpmesg \"%s\";\n", host.PMsg))
		}

		// Ping settings
		if host.SendPings > 0 {
			sb.WriteString(fmt.Sprintf("\tsend_pings %d;\n", host.SendPings))
		}
		if host.MinPings > 0 {
			sb.WriteString(fmt.Sprintf("\tmin_pings %d;\n", host.MinPings))
		}

		// SNMP settings
		if host.SNMPCommunity != "" {
			sb.WriteString(fmt.Sprintf("\tcommunity \"%s\";\n", host.SNMPCommunity))
		}
		if host.SNMPOID != "" {
			sb.WriteString(fmt.Sprintf("\toid \"%s\";\n", host.SNMPOID))
		}

		// DNS settings
		if host.DNSQuery != "" {
			sb.WriteString(fmt.Sprintf("\tdns-query \"%s\";\n", host.DNSQuery))
		}

		// HTTP settings
		if host.URL != "" {
			sb.WriteString(fmt.Sprintf("\turl \"%s\";\n", host.URL))
		}
		if host.URLText != "" {
			sb.WriteString(fmt.Sprintf("\turltext \"%s\";\n", host.URLText))
		}

		// Auth settings
		if host.Username != "" {
			sb.WriteString(fmt.Sprintf("\tusername \"%s\";\n", host.Username))
		}
		if host.Password != "" {
			sb.WriteString(fmt.Sprintf("\tpassword \"%s\";\n", host.Password))
		}
		if host.Secret != "" {
			sb.WriteString(fmt.Sprintf("\tsecret \"%s\";\n", host.Secret))
		}

		sb.WriteString("};\n\n")
	}

	return sb.String(), nil
}

// Validate validates a config
func Validate(config *models.Config) error {
	if config == nil {
		return fmt.Errorf("config is nil")
	}

	if len(config.Hosts) == 0 {
		return fmt.Errorf("no hosts configured")
	}

	hostnames := make(map[string]bool)
	for _, host := range config.Hosts {
		if host.Hostname == "" {
			return fmt.Errorf("host has empty hostname")
		}
		if hostnames[host.Hostname] {
			return fmt.Errorf("duplicate hostname: %s", host.Hostname)
		}
		hostnames[host.Hostname] = true
	}

	return nil
}
