package com.sysmon.app

import android.content.Context
import android.content.SharedPreferences
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

// Observable holder for the current FCM device token. Backed by plain
// SharedPreferences (the token is not sensitive — it's an FCM identifier
// and is regenerated by Firebase whenever Play Services rotates it).
object FcmTokenStore {
    private const val PREFS = "sysmon_fcm"
    private const val KEY = "fcm_token"

    private lateinit var prefs: SharedPreferences

    var token by mutableStateOf<String?>(null)
        private set

    fun init(context: Context) {
        prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        token = prefs.getString(KEY, null)
    }

    fun update(newToken: String?) {
        token = newToken
        if (newToken != null) {
            prefs.edit().putString(KEY, newToken).apply()
        } else {
            prefs.edit().remove(KEY).apply()
        }
    }
}
